version: '3.8'

# Docker Compose for Mac Mini - Mixed Deployment
# Docker: Orchestrator API + MongoDB
# Local: Docling Service + Neo4j Desktop

services:
  # MongoDB for storing user and chat data
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3

  # The main orchestrator API (connects to local docling service)
  orchestrator_api:
    build:
      context: ./orchestrator_api
      dockerfile: Dockerfile
    container_name: orchestrator_api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    env_file:
      - ./orchestrator_api/.env
    environment:
      # Override to connect to local docling service on host
      - DOCLING_SERVICE_URL=http://host.docker.internal:8004
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mongodb
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongo_data:

networks:
  default:
    name: document_library_network