services:
  orchestrator_api:
    build: ./orchestrator_api
    container_name: orchestrator_api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data # Mounts the local data directory into the container
    env_file:
      - ./orchestrator_api/.env
    # Use host networking to easily connect to localhost databases
    network_mode: "host"
