services:
  orchestrator_api:
    build: ./orchestrator_api
    container_name: orchestrator_api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    env_file:
      - ./orchestrator_api/.env