version: '3.8'

services:
  milvus:
    image: milvusdb/milvus:v2.4.4
    container_name: milvus_service
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - ./milvus_data:/milvus/data
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000